apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashemitter-dep
  namespace: exercises-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashemitter
  template:
    metadata:
      labels:
        app: hashemitter
    spec:
      volumes: # Define volume
        - name: shared-volume
          persistentVolumeClaim:
            claimName: volume-claim     
      containers:
        - name: reader
          image: sasumaki/reader:19FE4935-D56C-4FC6-A4F1-642FBE729720
          envFrom:
          - configMapRef:
              name: lol-config
          volumeMounts: # Mount volume
          - name: shared-volume
            mountPath: /go/src/app/files
          
  
        - name: hashemitter
          image: sasumaki/hashemitter:19FE4935-D56C-4FC6-A4F1-642FBE729720
          volumeMounts: # Mount volume
          - name: shared-volume
            mountPath: /go/src/app/files
