apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
  namespace: exercises-namespace

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
