apiVersion: v1
kind: Service
metadata:
  name: hashgenerator-svc
  namespace: exercises-namespace

spec:
  type: ClusterIP
  selector:
    app: hashemitter
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 8081
