apiVersion: apps/v1
kind: Deployment
metadata:
  name: ponger-dep
  namespace: exercises-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ponger-app
  template:
    metadata:
      labels:
        app: ponger-app
    spec:
      containers:
        - name: ponger-app
          image: sasumaki/ponger:BB87B65D-39B1-49BA-A854-8F13CDCE55C7
          envFrom:
          - configMapRef:
              name: postgres-config
