apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashemitter-dep
  namespace: exercises-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashemitter
  template:
    metadata:
      labels:
        app: hashemitter
    spec:
      volumes: # Define volume
        - name: shared-volume
          persistentVolumeClaim:
            claimName: volume-claim     
      containers:
        - name: reader
          image: sasumaki/reader:538DA5BC-6317-4391-B8E4-8331A36FDB96
          envFrom:
          - configMapRef:
              name: lol-config
          volumeMounts: # Mount volume
          - name: shared-volume
            mountPath: /go/src/app/files
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /health
               port: 8081
          
  
        - name: hashemitter
          image: sasumaki/hashemitter:538DA5BC-6317-4391-B8E4-8331A36FDB96
          volumeMounts: # Mount volume
          - name: shared-volume
            mountPath: /go/src/app/files
