apiVersion: v1
kind: Service
metadata:
  name: ponger-svc
  namespace: exercises-namespace

spec:
  type: ClusterIP
  selector:
    app: ponger-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  