apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: restart-rate
  namespace: todo-namespace
spec:
  metrics:
  - name: restart-rate
    initialDelay: 2m
    successCondition: result < 1000
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1602-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="todo-namespace"}[5m]))