apiVersion: v1
kind: Service
metadata:
  name: crud-svc
  namespace: todo-namespace

spec:
  type: ClusterIP
  selector:
    app: crud-app
  ports:
    - name: http
      port: 2345
      protocol: TCP
      targetPort: 8080

  