
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - stable.dwk.my.domain
  resources:
  - dummysites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.dwk.my.domain
  resources:
  - dummysites/status
  verbs:
  - get
  - patch
  - update
