apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      volumes: # Define volume
          - name: shared-volume
            persistentVolumeClaim:
              claimName: volume-claim
      containers:
        - name: crud-app
          image: sasumaki/crud-app:10
          volumeMounts: # Mount volume
            - name: shared-volume
              mountPath: /go/src/app/files